### ISSUE TITLE
Decreased performance in high number of frames

### ISSUE THREAD

**Issue by ehsaneona** [mediamonks/fast-image-sequence#21]
I have 1797 frames, and when the images are trying to load the performance drops drastically.

Demo: https://hi-and-buy.vercel.app

In fact, the problem is that the number of images to be loaded is large and the process of loading images takes a long time. How to solve this problem?

**Comment by reindernijhoff** [comment]
Hi, thanks for the feedback, I will try to fix the issues asap and let you know.

**Comment by reindernijhoff** [comment]
Can you upgrade to version 0.4.4 and check if this fixes the bug?

Options you can tweak:

- numberOfCachedImages (default 32, I think that is a nice amount, but maybe you can increase it)
- useWorkerForImage (default true, but this increases latency and maybe memory usage, so you could try setting this to false help)

Please let me know if this fixed your bug. Any suggestions for improving this package are very welcome.

Note: If your develop tab is open, performance will decrease over time due to the number of logged network requests. This will not happen when the tab is closed.
